export default {
  FINDER_SCREEN_ACTIONS: {
    SEARCH_BAR_TEXT: 'SEARCH_BAR_TEXT',
    FETCH_COCKTAILS_DATA_LOADING: 'FETCH_COCKTAILS_DATA_LOADING',
    FETCH_COCKTAILS_DATA_SUCCESS: 'FETCH_COCKTAILS_DATA_SUCCESS',
  }
}